name: say-hello
run-name: ${{github.actor}} just learning GH Actions
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1"
      - name: Run index
        run: bun run index.mjs
      - name: Log success message
        run: echo 🚀 My fisrt GH Action!!!
