name: say-hello
run-name: ${{github.actor}} jsut learning GH Actions
on: [push]
jobs:
  say-hello:
    runs-on: ubuntu@18
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1"
      - run: bun run index.mjs
      - run: echo 🚀 My fisrt GH Action!!!
